onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -group {TX 1} /test_tx_rs232/inst_tx_rs232_1/reset_n
add wave -noupdate -group {TX 1} /test_tx_rs232/inst_tx_rs232_1/clock
add wave -noupdate -group {TX 1} /test_tx_rs232/inst_tx_rs232_1/start_tx
add wave -noupdate -group {TX 1} /test_tx_rs232/inst_tx_rs232_1/tx_data
add wave -noupdate -group {TX 1} /test_tx_rs232/inst_tx_rs232_1/tx
add wave -noupdate -group {TX 1} /test_tx_rs232/inst_tx_rs232_1/tx_done
add wave -noupdate -group {TX 1} /test_tx_rs232/inst_tx_rs232_1/tx_fsm
add wave -noupdate -group {TX 1} /test_tx_rs232/inst_tx_rs232_1/start_tx_old
add wave -noupdate -group {TX 1} /test_tx_rs232/inst_tx_rs232_1/start_tx_re
add wave -noupdate -group {TX 1} /test_tx_rs232/inst_tx_rs232_1/tx_data_s
add wave -noupdate -group {TX 1} /test_tx_rs232/inst_tx_rs232_1/tx_s
add wave -noupdate -group {TX 1} /test_tx_rs232/inst_tx_rs232_1/cnt_bit_duration
add wave -noupdate -group {TX 1} /test_tx_rs232/inst_tx_rs232_1/tick_data
add wave -noupdate -group {TX 1} /test_tx_rs232/inst_tx_rs232_1/cnt_data
add wave -noupdate -group {TX 1} /test_tx_rs232/inst_tx_rs232_1/cnt_bit
add wave -noupdate -group {TX 1} /test_tx_rs232/inst_tx_rs232_1/cnt_stop_bit
add wave -noupdate -group {TX 1} /test_tx_rs232/inst_tx_rs232_1/tx_done_s
add wave -noupdate -group {TX 1} /test_tx_rs232/inst_tx_rs232_1/parity_value
add wave -noupdate -group {RX 1} /test_tx_rs232/inst_rx_uart_1/reset_n
add wave -noupdate -group {RX 1} /test_tx_rs232/inst_rx_uart_1/clock
add wave -noupdate -group {RX 1} /test_tx_rs232/inst_rx_uart_1/rx
add wave -noupdate -group {RX 1} /test_tx_rs232/inst_rx_uart_1/rx_data
add wave -noupdate -group {RX 1} /test_tx_rs232/inst_rx_uart_1/rx_done
add wave -noupdate -group {RX 1} /test_tx_rs232/inst_rx_uart_1/parity_rcvd
add wave -noupdate -group {RX 1} /test_tx_rs232/inst_rx_uart_1/rx_fsm
add wave -noupdate -group {RX 1} /test_tx_rs232/inst_rx_uart_1/rx_old
add wave -noupdate -group {RX 1} /test_tx_rs232/inst_rx_uart_1/start_rx_fe
add wave -noupdate -group {RX 1} /test_tx_rs232/inst_rx_uart_1/start_rx_re
add wave -noupdate -group {RX 1} /test_tx_rs232/inst_rx_uart_1/start_cnt
add wave -noupdate -group {RX 1} /test_tx_rs232/inst_rx_uart_1/tick_data
add wave -noupdate -group {RX 1} /test_tx_rs232/inst_rx_uart_1/rx_data_s
add wave -noupdate -group {RX 1} /test_tx_rs232/inst_rx_uart_1/cnt_half_bit
add wave -noupdate -group {RX 1} /test_tx_rs232/inst_rx_uart_1/cnt_bit
add wave -noupdate -group {RX 1} /test_tx_rs232/inst_rx_uart_1/cnt_data
add wave -noupdate -group {TX 2} /test_tx_rs232/inst_tx_rs232_2/reset_n
add wave -noupdate -group {TX 2} /test_tx_rs232/inst_tx_rs232_2/clock
add wave -noupdate -group {TX 2} /test_tx_rs232/inst_tx_rs232_2/start_tx
add wave -noupdate -group {TX 2} /test_tx_rs232/inst_tx_rs232_2/tx_data
add wave -noupdate -group {TX 2} /test_tx_rs232/inst_tx_rs232_2/tx
add wave -noupdate -group {TX 2} /test_tx_rs232/inst_tx_rs232_2/tx_done
add wave -noupdate -group {TX 2} /test_tx_rs232/inst_tx_rs232_2/tx_fsm
add wave -noupdate -group {TX 2} /test_tx_rs232/inst_tx_rs232_2/start_tx_old
add wave -noupdate -group {TX 2} /test_tx_rs232/inst_tx_rs232_2/start_tx_re
add wave -noupdate -group {TX 2} /test_tx_rs232/inst_tx_rs232_2/tx_data_s
add wave -noupdate -group {TX 2} /test_tx_rs232/inst_tx_rs232_2/tx_s
add wave -noupdate -group {TX 2} /test_tx_rs232/inst_tx_rs232_2/cnt_bit_duration
add wave -noupdate -group {TX 2} /test_tx_rs232/inst_tx_rs232_2/tick_data
add wave -noupdate -group {TX 2} /test_tx_rs232/inst_tx_rs232_2/cnt_data
add wave -noupdate -group {TX 2} /test_tx_rs232/inst_tx_rs232_2/cnt_bit
add wave -noupdate -group {TX 2} /test_tx_rs232/inst_tx_rs232_2/cnt_stop_bit
add wave -noupdate -group {TX 2} /test_tx_rs232/inst_tx_rs232_2/tx_done_s
add wave -noupdate -group {TX 2} /test_tx_rs232/inst_tx_rs232_2/parity_value
add wave -noupdate -group {RX 2} /test_tx_rs232/inst_rx_uart_2/reset_n
add wave -noupdate -group {RX 2} /test_tx_rs232/inst_rx_uart_2/clock
add wave -noupdate -group {RX 2} /test_tx_rs232/inst_rx_uart_2/rx
add wave -noupdate -group {RX 2} /test_tx_rs232/inst_rx_uart_2/rx_data
add wave -noupdate -group {RX 2} /test_tx_rs232/inst_rx_uart_2/rx_done
add wave -noupdate -group {RX 2} /test_tx_rs232/inst_rx_uart_2/parity_rcvd
add wave -noupdate -group {RX 2} /test_tx_rs232/inst_rx_uart_2/rx_fsm
add wave -noupdate -group {RX 2} /test_tx_rs232/inst_rx_uart_2/rx_old
add wave -noupdate -group {RX 2} /test_tx_rs232/inst_rx_uart_2/start_rx_fe
add wave -noupdate -group {RX 2} /test_tx_rs232/inst_rx_uart_2/start_rx_re
add wave -noupdate -group {RX 2} /test_tx_rs232/inst_rx_uart_2/start_cnt
add wave -noupdate -group {RX 2} /test_tx_rs232/inst_rx_uart_2/tick_data
add wave -noupdate -group {RX 2} /test_tx_rs232/inst_rx_uart_2/rx_data_s
add wave -noupdate -group {RX 2} /test_tx_rs232/inst_rx_uart_2/parity_rcvd_s
add wave -noupdate -group {RX 2} /test_tx_rs232/inst_rx_uart_2/rx_done_s
add wave -noupdate -group {RX 2} /test_tx_rs232/inst_rx_uart_2/cnt_half_bit
add wave -noupdate -group {RX 2} /test_tx_rs232/inst_rx_uart_2/cnt_bit
add wave -noupdate -group {RX 2} /test_tx_rs232/inst_rx_uart_2/cnt_data
add wave -noupdate -group {RX 2} /test_tx_rs232/inst_rx_uart_2/cnt_stop_bit
add wave -noupdate -group {TX 3} /test_tx_rs232/inst_tx_rs232_3/reset_n
add wave -noupdate -group {TX 3} /test_tx_rs232/inst_tx_rs232_3/clock
add wave -noupdate -group {TX 3} /test_tx_rs232/inst_tx_rs232_3/start_tx
add wave -noupdate -group {TX 3} /test_tx_rs232/inst_tx_rs232_3/tx_data
add wave -noupdate -group {TX 3} /test_tx_rs232/inst_tx_rs232_3/tx
add wave -noupdate -group {TX 3} /test_tx_rs232/inst_tx_rs232_3/tx_done
add wave -noupdate -group {TX 3} /test_tx_rs232/inst_tx_rs232_3/tx_fsm
add wave -noupdate -group {TX 3} /test_tx_rs232/inst_tx_rs232_3/start_tx_old
add wave -noupdate -group {TX 3} /test_tx_rs232/inst_tx_rs232_3/start_tx_re
add wave -noupdate -group {TX 3} /test_tx_rs232/inst_tx_rs232_3/tx_data_s
add wave -noupdate -group {TX 3} /test_tx_rs232/inst_tx_rs232_3/tx_s
add wave -noupdate -group {TX 3} /test_tx_rs232/inst_tx_rs232_3/cnt_bit_duration
add wave -noupdate -group {TX 3} /test_tx_rs232/inst_tx_rs232_3/tick_data
add wave -noupdate -group {TX 3} /test_tx_rs232/inst_tx_rs232_3/cnt_data
add wave -noupdate -group {TX 3} /test_tx_rs232/inst_tx_rs232_3/cnt_bit
add wave -noupdate -group {TX 3} /test_tx_rs232/inst_tx_rs232_3/cnt_stop_bit
add wave -noupdate -group {TX 3} /test_tx_rs232/inst_tx_rs232_3/tx_done_s
add wave -noupdate -group {TX 3} /test_tx_rs232/inst_tx_rs232_3/parity_value
add wave -noupdate -group {RX 3} /test_tx_rs232/inst_rx_uart_3/reset_n
add wave -noupdate -group {RX 3} /test_tx_rs232/inst_rx_uart_3/clock
add wave -noupdate -group {RX 3} /test_tx_rs232/inst_rx_uart_3/rx
add wave -noupdate -group {RX 3} /test_tx_rs232/inst_rx_uart_3/rx_data
add wave -noupdate -group {RX 3} /test_tx_rs232/inst_rx_uart_3/rx_done
add wave -noupdate -group {RX 3} /test_tx_rs232/inst_rx_uart_3/parity_rcvd
add wave -noupdate -group {RX 3} /test_tx_rs232/inst_rx_uart_3/rx_fsm
add wave -noupdate -group {RX 3} /test_tx_rs232/inst_rx_uart_3/rx_old
add wave -noupdate -group {RX 3} /test_tx_rs232/inst_rx_uart_3/start_rx_fe
add wave -noupdate -group {RX 3} /test_tx_rs232/inst_rx_uart_3/start_rx_re
add wave -noupdate -group {RX 3} /test_tx_rs232/inst_rx_uart_3/start_cnt
add wave -noupdate -group {RX 3} /test_tx_rs232/inst_rx_uart_3/tick_data
add wave -noupdate -group {RX 3} /test_tx_rs232/inst_rx_uart_3/rx_data_s
add wave -noupdate -group {RX 3} /test_tx_rs232/inst_rx_uart_3/parity_rcvd_s
add wave -noupdate -group {RX 3} /test_tx_rs232/inst_rx_uart_3/rx_done_s
add wave -noupdate -group {RX 3} /test_tx_rs232/inst_rx_uart_3/cnt_half_bit
add wave -noupdate -group {RX 3} /test_tx_rs232/inst_rx_uart_3/cnt_bit
add wave -noupdate -group {RX 3} /test_tx_rs232/inst_rx_uart_3/cnt_data
add wave -noupdate -group {RX 3} /test_tx_rs232/inst_rx_uart_3/cnt_stop_bit
add wave -noupdate -group {TX 4} /test_tx_rs232/inst_tx_rs232_4/reset_n
add wave -noupdate -group {TX 4} /test_tx_rs232/inst_tx_rs232_4/clock
add wave -noupdate -group {TX 4} /test_tx_rs232/inst_tx_rs232_4/start_tx
add wave -noupdate -group {TX 4} /test_tx_rs232/inst_tx_rs232_4/tx_data
add wave -noupdate -group {TX 4} /test_tx_rs232/inst_tx_rs232_4/tx
add wave -noupdate -group {TX 4} /test_tx_rs232/inst_tx_rs232_4/tx_done
add wave -noupdate -group {TX 4} /test_tx_rs232/inst_tx_rs232_4/tx_fsm
add wave -noupdate -group {TX 4} /test_tx_rs232/inst_tx_rs232_4/start_tx_old
add wave -noupdate -group {TX 4} /test_tx_rs232/inst_tx_rs232_4/start_tx_re
add wave -noupdate -group {TX 4} /test_tx_rs232/inst_tx_rs232_4/tx_data_s
add wave -noupdate -group {TX 4} /test_tx_rs232/inst_tx_rs232_4/tx_s
add wave -noupdate -group {TX 4} /test_tx_rs232/inst_tx_rs232_4/cnt_bit_duration
add wave -noupdate -group {TX 4} /test_tx_rs232/inst_tx_rs232_4/tick_data
add wave -noupdate -group {TX 4} /test_tx_rs232/inst_tx_rs232_4/cnt_data
add wave -noupdate -group {TX 4} /test_tx_rs232/inst_tx_rs232_4/cnt_bit
add wave -noupdate -group {TX 4} /test_tx_rs232/inst_tx_rs232_4/cnt_stop_bit
add wave -noupdate -group {TX 4} /test_tx_rs232/inst_tx_rs232_4/tx_done_s
add wave -noupdate -group {TX 4} /test_tx_rs232/inst_tx_rs232_4/parity_value
add wave -noupdate -group {RX 4} /test_tx_rs232/inst_rx_uart_4/reset_n
add wave -noupdate -group {RX 4} /test_tx_rs232/inst_rx_uart_4/clock
add wave -noupdate -group {RX 4} /test_tx_rs232/inst_rx_uart_4/rx
add wave -noupdate -group {RX 4} /test_tx_rs232/inst_rx_uart_4/rx_data
add wave -noupdate -group {RX 4} /test_tx_rs232/inst_rx_uart_4/rx_done
add wave -noupdate -group {RX 4} /test_tx_rs232/inst_rx_uart_4/parity_rcvd
add wave -noupdate -group {RX 4} /test_tx_rs232/inst_rx_uart_4/rx_fsm
add wave -noupdate -group {RX 4} /test_tx_rs232/inst_rx_uart_4/rx_old
add wave -noupdate -group {RX 4} /test_tx_rs232/inst_rx_uart_4/start_rx_fe
add wave -noupdate -group {RX 4} /test_tx_rs232/inst_rx_uart_4/start_rx_re
add wave -noupdate -group {RX 4} /test_tx_rs232/inst_rx_uart_4/start_cnt
add wave -noupdate -group {RX 4} /test_tx_rs232/inst_rx_uart_4/tick_data
add wave -noupdate -group {RX 4} /test_tx_rs232/inst_rx_uart_4/rx_data_s
add wave -noupdate -group {RX 4} /test_tx_rs232/inst_rx_uart_4/parity_rcvd_s
add wave -noupdate -group {RX 4} /test_tx_rs232/inst_rx_uart_4/rx_done_s
add wave -noupdate -group {RX 4} /test_tx_rs232/inst_rx_uart_4/cnt_half_bit
add wave -noupdate -group {RX 4} /test_tx_rs232/inst_rx_uart_4/cnt_bit
add wave -noupdate -group {RX 4} /test_tx_rs232/inst_rx_uart_4/cnt_data
add wave -noupdate -group {RX 4} /test_tx_rs232/inst_rx_uart_4/cnt_stop_bit
add wave -noupdate -group {TX 5} /test_tx_rs232/inst_tx_rs232_5/reset_n
add wave -noupdate -group {TX 5} /test_tx_rs232/inst_tx_rs232_5/clock
add wave -noupdate -group {TX 5} /test_tx_rs232/inst_tx_rs232_5/start_tx
add wave -noupdate -group {TX 5} /test_tx_rs232/inst_tx_rs232_5/tx_data
add wave -noupdate -group {TX 5} /test_tx_rs232/inst_tx_rs232_5/tx
add wave -noupdate -group {TX 5} /test_tx_rs232/inst_tx_rs232_5/tx_done
add wave -noupdate -group {TX 5} /test_tx_rs232/inst_tx_rs232_5/tx_fsm
add wave -noupdate -group {TX 5} /test_tx_rs232/inst_tx_rs232_5/start_tx_old
add wave -noupdate -group {TX 5} /test_tx_rs232/inst_tx_rs232_5/start_tx_re
add wave -noupdate -group {TX 5} /test_tx_rs232/inst_tx_rs232_5/tx_data_s
add wave -noupdate -group {TX 5} /test_tx_rs232/inst_tx_rs232_5/tx_s
add wave -noupdate -group {TX 5} /test_tx_rs232/inst_tx_rs232_5/cnt_bit_duration
add wave -noupdate -group {TX 5} /test_tx_rs232/inst_tx_rs232_5/tick_data
add wave -noupdate -group {TX 5} /test_tx_rs232/inst_tx_rs232_5/cnt_data
add wave -noupdate -group {TX 5} /test_tx_rs232/inst_tx_rs232_5/cnt_bit
add wave -noupdate -group {TX 5} /test_tx_rs232/inst_tx_rs232_5/cnt_stop_bit
add wave -noupdate -group {TX 5} /test_tx_rs232/inst_tx_rs232_5/tx_done_s
add wave -noupdate -group {TX 5} /test_tx_rs232/inst_tx_rs232_5/parity_value
add wave -noupdate -group {RX 5} /test_tx_rs232/inst_rx_uart_5/reset_n
add wave -noupdate -group {RX 5} /test_tx_rs232/inst_rx_uart_5/clock
add wave -noupdate -group {RX 5} /test_tx_rs232/inst_rx_uart_5/rx
add wave -noupdate -group {RX 5} /test_tx_rs232/inst_rx_uart_5/rx_data
add wave -noupdate -group {RX 5} /test_tx_rs232/inst_rx_uart_5/rx_done
add wave -noupdate -group {RX 5} /test_tx_rs232/inst_rx_uart_5/parity_rcvd
add wave -noupdate -group {RX 5} /test_tx_rs232/inst_rx_uart_5/rx_fsm
add wave -noupdate -group {RX 5} /test_tx_rs232/inst_rx_uart_5/rx_old
add wave -noupdate -group {RX 5} /test_tx_rs232/inst_rx_uart_5/start_rx_fe
add wave -noupdate -group {RX 5} /test_tx_rs232/inst_rx_uart_5/start_rx_re
add wave -noupdate -group {RX 5} /test_tx_rs232/inst_rx_uart_5/start_cnt
add wave -noupdate -group {RX 5} /test_tx_rs232/inst_rx_uart_5/tick_data
add wave -noupdate -group {RX 5} /test_tx_rs232/inst_rx_uart_5/rx_data_s
add wave -noupdate -group {RX 5} /test_tx_rs232/inst_rx_uart_5/parity_rcvd_s
add wave -noupdate -group {RX 5} /test_tx_rs232/inst_rx_uart_5/rx_done_s
add wave -noupdate -group {RX 5} /test_tx_rs232/inst_rx_uart_5/cnt_half_bit
add wave -noupdate -group {RX 5} /test_tx_rs232/inst_rx_uart_5/cnt_bit
add wave -noupdate -group {RX 5} /test_tx_rs232/inst_rx_uart_5/cnt_data
add wave -noupdate -group {RX 5} /test_tx_rs232/inst_rx_uart_5/cnt_stop_bit
add wave -noupdate -group {TX 6} /test_tx_rs232/inst_tx_rs232_6/reset_n
add wave -noupdate -group {TX 6} /test_tx_rs232/inst_tx_rs232_6/clock
add wave -noupdate -group {TX 6} /test_tx_rs232/inst_tx_rs232_6/start_tx
add wave -noupdate -group {TX 6} /test_tx_rs232/inst_tx_rs232_6/tx_data
add wave -noupdate -group {TX 6} /test_tx_rs232/inst_tx_rs232_6/tx
add wave -noupdate -group {TX 6} /test_tx_rs232/inst_tx_rs232_6/tx_done
add wave -noupdate -group {TX 6} /test_tx_rs232/inst_tx_rs232_6/tx_fsm
add wave -noupdate -group {TX 6} /test_tx_rs232/inst_tx_rs232_6/start_tx_old
add wave -noupdate -group {TX 6} /test_tx_rs232/inst_tx_rs232_6/start_tx_re
add wave -noupdate -group {TX 6} /test_tx_rs232/inst_tx_rs232_6/tx_data_s
add wave -noupdate -group {TX 6} /test_tx_rs232/inst_tx_rs232_6/tx_s
add wave -noupdate -group {TX 6} /test_tx_rs232/inst_tx_rs232_6/cnt_bit_duration
add wave -noupdate -group {TX 6} /test_tx_rs232/inst_tx_rs232_6/tick_data
add wave -noupdate -group {TX 6} /test_tx_rs232/inst_tx_rs232_6/cnt_data
add wave -noupdate -group {TX 6} /test_tx_rs232/inst_tx_rs232_6/cnt_bit
add wave -noupdate -group {TX 6} /test_tx_rs232/inst_tx_rs232_6/cnt_stop_bit
add wave -noupdate -group {TX 6} /test_tx_rs232/inst_tx_rs232_6/tx_done_s
add wave -noupdate -group {TX 6} /test_tx_rs232/inst_tx_rs232_6/parity_value
add wave -noupdate -group {RX 6} /test_tx_rs232/inst_rx_uart_6/reset_n
add wave -noupdate -group {RX 6} /test_tx_rs232/inst_rx_uart_6/clock
add wave -noupdate -group {RX 6} /test_tx_rs232/inst_rx_uart_6/rx
add wave -noupdate -group {RX 6} /test_tx_rs232/inst_rx_uart_6/rx_data
add wave -noupdate -group {RX 6} /test_tx_rs232/inst_rx_uart_6/rx_done
add wave -noupdate -group {RX 6} /test_tx_rs232/inst_rx_uart_6/parity_rcvd
add wave -noupdate -group {RX 6} /test_tx_rs232/inst_rx_uart_6/rx_fsm
add wave -noupdate -group {RX 6} /test_tx_rs232/inst_rx_uart_6/rx_old
add wave -noupdate -group {RX 6} /test_tx_rs232/inst_rx_uart_6/start_rx_fe
add wave -noupdate -group {RX 6} /test_tx_rs232/inst_rx_uart_6/start_rx_re
add wave -noupdate -group {RX 6} /test_tx_rs232/inst_rx_uart_6/start_cnt
add wave -noupdate -group {RX 6} /test_tx_rs232/inst_rx_uart_6/tick_data
add wave -noupdate -group {RX 6} /test_tx_rs232/inst_rx_uart_6/rx_data_s
add wave -noupdate -group {RX 6} /test_tx_rs232/inst_rx_uart_6/parity_rcvd_s
add wave -noupdate -group {RX 6} /test_tx_rs232/inst_rx_uart_6/rx_done_s
add wave -noupdate -group {RX 6} /test_tx_rs232/inst_rx_uart_6/cnt_half_bit
add wave -noupdate -group {RX 6} /test_tx_rs232/inst_rx_uart_6/cnt_bit
add wave -noupdate -group {RX 6} /test_tx_rs232/inst_rx_uart_6/cnt_data
add wave -noupdate -group {RX 6} /test_tx_rs232/inst_rx_uart_6/cnt_stop_bit
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {110876260 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 198
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 1
configure wave -timelineunits us
update
WaveRestoreZoom {0 ps} {1050 us}
