# -- INCLUDES --
include /home/linux-jp/Documents/GitHub/Generics_Makefiles/Makefiles/MakefileGeneric
include /home/linux-jp/Documents/GitHub/RTL_Testbench/scripts/makefiles/generic_modules_files.mk
include /home/linux-jp/Documents/GitHub/RTL_Testbench/scripts/makefiles/tb_modules_lib_path.mk
include MakefileSPI_MASTER.mk
# --------------



# -- MODELSIM Configuration --
vsim=/opt/Modelsim/modelsim_ase/bin/vsim
vlib=/opt/Modelsim/modelsim_ase/linuxaloem/vlib
vmap=/opt/Modelsim/modelsim_ase/linuxaloem/vmap
vcom=/opt/Modelsim/modelsim_ase/linuxaloem/vcom
vlog=/opt/Modelsim/modelsim_ase/linuxaloem/vlog
# ----------------------------


all:
	echo "Makefile for SPI"
